#!/bin/bash

set -exuo pipefail

dmg='ProToolsExtraAIRInstruments-2018.3-1.dmg'
vol="$(hdiutil attach $dmg  | tail -1 | awk -F '\t' '{print $3}')"

pkg="${vol}/Install First AIR Instruments Bundle.pkg"

installer -pkg "${pkg}" -target / -dumplog

sleep 5

diskutil unmount "${vol}"

# Set content paths for AIR Instruments
/usr/bin/defaults write /Library/Preferences/com.airmusictech.Boom Content -string "/Applications/AIR Music Technology/Boom"
/usr/bin/defaults write /Library/Preferences/com.airmusictech.Mini\ Grand Content -string "/Applications/AIR Music Technology/Mini Grand"
/bin/chmod 644 /Library/Preferences/com.airmusictech.Boom.plist
/bin/chmod 644 /Library/Preferences/com.airmusictech.Mini\ Grand.plist


exit 0   
